/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.treinamento.contato.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Contato service. Represents a row in the &quot;Contato_Contato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.treinamento.contato.model.impl.ContatoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.treinamento.contato.model.impl.ContatoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Contato
 * @generated
 */
@ProviderType
public interface ContatoModel
	extends BaseModel<Contato>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contato model instance should use the {@link Contato} interface instead.
	 */

	/**
	 * Returns the primary key of this contato.
	 *
	 * @return the primary key of this contato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contato.
	 *
	 * @param primaryKey the primary key of this contato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contato.
	 *
	 * @return the uuid of this contato
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contato.
	 *
	 * @param uuid the uuid of this contato
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the contato ID of this contato.
	 *
	 * @return the contato ID of this contato
	 */
	public long getContatoId();

	/**
	 * Sets the contato ID of this contato.
	 *
	 * @param contatoId the contato ID of this contato
	 */
	public void setContatoId(long contatoId);

	/**
	 * Returns the group ID of this contato.
	 *
	 * @return the group ID of this contato
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contato.
	 *
	 * @param groupId the group ID of this contato
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contato.
	 *
	 * @return the company ID of this contato
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contato.
	 *
	 * @param companyId the company ID of this contato
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contato.
	 *
	 * @return the user ID of this contato
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contato.
	 *
	 * @param userId the user ID of this contato
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contato.
	 *
	 * @return the user uuid of this contato
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contato.
	 *
	 * @param userUuid the user uuid of this contato
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contato.
	 *
	 * @return the user name of this contato
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contato.
	 *
	 * @param userName the user name of this contato
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contato.
	 *
	 * @return the create date of this contato
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contato.
	 *
	 * @param createDate the create date of this contato
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contato.
	 *
	 * @return the modified date of this contato
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contato.
	 *
	 * @param modifiedDate the modified date of this contato
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this contato.
	 *
	 * @return the nome of this contato
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this contato.
	 *
	 * @param nome the nome of this contato
	 */
	public void setNome(String nome);

	/**
	 * Returns the telefone of this contato.
	 *
	 * @return the telefone of this contato
	 */
	@AutoEscape
	public String getTelefone();

	/**
	 * Sets the telefone of this contato.
	 *
	 * @param telefone the telefone of this contato
	 */
	public void setTelefone(String telefone);

	/**
	 * Returns the idade of this contato.
	 *
	 * @return the idade of this contato
	 */
	public int getIdade();

	/**
	 * Sets the idade of this contato.
	 *
	 * @param idade the idade of this contato
	 */
	public void setIdade(int idade);

	/**
	 * Returns the email of this contato.
	 *
	 * @return the email of this contato
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this contato.
	 *
	 * @param email the email of this contato
	 */
	public void setEmail(String email);

	@Override
	public Contato cloneWithOriginalValues();

}