/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.treinamento.contato.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.treinamento.contato.model.Contato;
import com.liferay.treinamento.contato.model.ContatoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Contato service. Represents a row in the &quot;Contato_Contato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContatoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContatoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContatoImpl
 * @generated
 */
@JSON(strict = true)
public class ContatoModelImpl
	extends BaseModelImpl<Contato> implements ContatoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contato model instance should use the <code>Contato</code> interface instead.
	 */
	public static final String TABLE_NAME = "Contato_Contato";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"contatoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"telefone", Types.VARCHAR},
		{"idade", Types.INTEGER}, {"email", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contatoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telefone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idade", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Contato_Contato (uuid_ VARCHAR(75) null,contatoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,telefone VARCHAR(75) null,idade INTEGER,email VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Contato_Contato";

	public static final String ORDER_BY_JPQL = " ORDER BY contato.nome ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Contato_Contato.nome ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ContatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contatoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContatoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contatoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Contato.class;
	}

	@Override
	public String getModelClassName() {
		return Contato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Contato)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Contato, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Contato, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Contato)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Contato, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Contato, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Contato, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Contato, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Contato, Object>>();
		Map<String, BiConsumer<Contato, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Contato, ?>>();

		attributeGetterFunctions.put("uuid", Contato::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Contato, String>)Contato::setUuid);
		attributeGetterFunctions.put("contatoId", Contato::getContatoId);
		attributeSetterBiConsumers.put(
			"contatoId", (BiConsumer<Contato, Long>)Contato::setContatoId);
		attributeGetterFunctions.put("groupId", Contato::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Contato, Long>)Contato::setGroupId);
		attributeGetterFunctions.put("companyId", Contato::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Contato, Long>)Contato::setCompanyId);
		attributeGetterFunctions.put("userId", Contato::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Contato, Long>)Contato::setUserId);
		attributeGetterFunctions.put("userName", Contato::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Contato, String>)Contato::setUserName);
		attributeGetterFunctions.put("createDate", Contato::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Contato, Date>)Contato::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Contato::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Contato, Date>)Contato::setModifiedDate);
		attributeGetterFunctions.put("nome", Contato::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Contato, String>)Contato::setNome);
		attributeGetterFunctions.put("telefone", Contato::getTelefone);
		attributeSetterBiConsumers.put(
			"telefone", (BiConsumer<Contato, String>)Contato::setTelefone);
		attributeGetterFunctions.put("idade", Contato::getIdade);
		attributeSetterBiConsumers.put(
			"idade", (BiConsumer<Contato, Integer>)Contato::setIdade);
		attributeGetterFunctions.put("email", Contato::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Contato, String>)Contato::setEmail);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getContatoId() {
		return _contatoId;
	}

	@Override
	public void setContatoId(long contatoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contatoId = contatoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nome = nome;
	}

	@JSON
	@Override
	public String getTelefone() {
		if (_telefone == null) {
			return "";
		}
		else {
			return _telefone;
		}
	}

	@Override
	public void setTelefone(String telefone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_telefone = telefone;
	}

	@JSON
	@Override
	public int getIdade() {
		return _idade;
	}

	@Override
	public void setIdade(int idade) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idade = idade;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Contato.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Contato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Contato toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Contato>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContatoImpl contatoImpl = new ContatoImpl();

		contatoImpl.setUuid(getUuid());
		contatoImpl.setContatoId(getContatoId());
		contatoImpl.setGroupId(getGroupId());
		contatoImpl.setCompanyId(getCompanyId());
		contatoImpl.setUserId(getUserId());
		contatoImpl.setUserName(getUserName());
		contatoImpl.setCreateDate(getCreateDate());
		contatoImpl.setModifiedDate(getModifiedDate());
		contatoImpl.setNome(getNome());
		contatoImpl.setTelefone(getTelefone());
		contatoImpl.setIdade(getIdade());
		contatoImpl.setEmail(getEmail());

		contatoImpl.resetOriginalValues();

		return contatoImpl;
	}

	@Override
	public Contato cloneWithOriginalValues() {
		ContatoImpl contatoImpl = new ContatoImpl();

		contatoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		contatoImpl.setContatoId(
			this.<Long>getColumnOriginalValue("contatoId"));
		contatoImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		contatoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		contatoImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		contatoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		contatoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		contatoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		contatoImpl.setNome(this.<String>getColumnOriginalValue("nome"));
		contatoImpl.setTelefone(
			this.<String>getColumnOriginalValue("telefone"));
		contatoImpl.setIdade(this.<Integer>getColumnOriginalValue("idade"));
		contatoImpl.setEmail(this.<String>getColumnOriginalValue("email"));

		return contatoImpl;
	}

	@Override
	public int compareTo(Contato contato) {
		int value = 0;

		value = getNome().compareTo(contato.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Contato)) {
			return false;
		}

		Contato contato = (Contato)object;

		long primaryKey = contato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Contato> toCacheModel() {
		ContatoCacheModel contatoCacheModel = new ContatoCacheModel();

		contatoCacheModel.uuid = getUuid();

		String uuid = contatoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contatoCacheModel.uuid = null;
		}

		contatoCacheModel.contatoId = getContatoId();

		contatoCacheModel.groupId = getGroupId();

		contatoCacheModel.companyId = getCompanyId();

		contatoCacheModel.userId = getUserId();

		contatoCacheModel.userName = getUserName();

		String userName = contatoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contatoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contatoCacheModel.createDate = createDate.getTime();
		}
		else {
			contatoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contatoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contatoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contatoCacheModel.nome = getNome();

		String nome = contatoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			contatoCacheModel.nome = null;
		}

		contatoCacheModel.telefone = getTelefone();

		String telefone = contatoCacheModel.telefone;

		if ((telefone != null) && (telefone.length() == 0)) {
			contatoCacheModel.telefone = null;
		}

		contatoCacheModel.idade = getIdade();

		contatoCacheModel.email = getEmail();

		String email = contatoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			contatoCacheModel.email = null;
		}

		return contatoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Contato)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Contato)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Contato>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Contato.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _contatoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nome;
	private String _telefone;
	private int _idade;
	private String _email;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Contato, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Contato)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("contatoId", _contatoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nome", _nome);
		_columnOriginalValues.put("telefone", _telefone);
		_columnOriginalValues.put("idade", _idade);
		_columnOriginalValues.put("email", _email);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("contatoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("nome", 256L);

		columnBitmasks.put("telefone", 512L);

		columnBitmasks.put("idade", 1024L);

		columnBitmasks.put("email", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Contato _escapedModel;

}